---
plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

require:
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - spec/dummy/**/*

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

##########
# LAYOUT #
##########

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

#########
# RSPEC #
#########

RSpec/MultipleExpectations:
  Max: 2

RSpec/NamedSubject:
  Enabled: false

RSpecRails/HttpStatus:
  EnforcedStyle: numeric
